name: Update Projects Section

on:
  schedule:
    - cron: '0 0 * * 1'  # हर सोमवार
  workflow_dispatch:

jobs:
  update-projects:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies & Run Script
        run: |
          npm install axios
          node .github/scripts/update-projects.js

      - name: Commit and Push Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated project section" || echo "No changes"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
