name: Update Projects Section

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday
  workflow_dispatch:

jobs:
  update-projects:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Update Script
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - run: |
          npm install axios
          node .github/scripts/update-projects.js

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated project section" || echo "No changes"
          git push
